[package]
name = "cargo-watch"
version = "2.0.1"
authors = [
  "Félix Saparelli <felix@passcod.name>",
  "Antti Keränen <detegr@gmail.com>"
]

description = "Utility for cargo to compile projects when sources change"
homepage = "https://github.com/passcod/cargo-watch"
repository = "https://github.com/passcod/cargo-watch"

readme = "README.md"
license = "CC0-1.0"
keywords = [
  "cargo",
  "watch",
  "compile",
  "notify"
]

[dependencies]
rustc-serialize = "*"
docopt = "0.6"
docopt_macros = "0.6"
notify = "1.1"
regex = "*"
time = "*"
