[package]

name = "cargo-watch"
version = "1.0.2"
authors = ["Félix Saparelli <felix@passcod.name>"]

[dependencies]
time = "*"

[dependencies.inotify]
git = "https://github.com/hannobraun/inotify-rs.git"
